### ISSUE TITLE
Current proposal for intensities, mass and fragment ion annotations

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzSpecLib#20]
@edeutsch @RalfG: 

We have one request in mzTab to encode the information of the peptide identified from the spectral library into optional columns. The user wants to encode: 

- array intensities, 
- array masses
- array of annotations. 

I can't find this information in the current proposal. Can you point me to the document that contains this.

**Comment by edeutsch** [comment]
We are about 95% finished, but there are still a few minor details being worked out. Is the idea that the extra columns will be lists of all these values? So the masses column would be 126.127726;127.124761;128.134436 ?

**Comment by ypriverol** [comment]
Yes @edeutsch until we have a new version of mztab to encode these use cases a good approach will be to encode something like: 

| spectrum masses          | spectrum intensities | ion annotations |
|--------------------------|----------------------|-----------------|
| 1234.4, 346.899, 456.456 | 12.7, 1.345, 54.34   | ?               |

of course everything in the header with the corresponding CvTerms.

**Comment by RalfG** [comment]
Here's the current [work document for the peak annotation format](https://docs.google.com/document/d/1yEUNG4Ump6vnbMDs4iV4s3XISflmOkRAyqUuutcCG2w/edit?usp=sharing). And for completeness, here's the [draft specification document](https://docs.google.com/document/d/1l87lIyKTy2ti5yU7aqsLr7uX5jIU1dO7gEzyqWD2uQA/edit?usp=sharing) (which is still in an early stage).

**Comment by ypriverol** [comment]
Another option @edeutsch instead of encoding the intensities, masses, and annotations in the mzTab is to have a reference to a spectral library file that contains that information for the experiment. In the mzTab, we only need to add the reference in the file.

BTW, @RalfG @edeutsch do we have an identifier of each spectrum in the library or it is by index as other file formats.

**Comment by edeutsch** [comment]
The new mzSpecLib format has a numerical index id for every entry (1,2,3,4,5,...)
SpectraST splib format has a numerical index id for every entry (0,1,2,3,4,5,...)
MSP does not have an index or an id, but has a "name" field that is nominally supposed to be unique, although I don't know how strictly that is followed.

**Comment by edeutsch** [comment]
I do think it would be better to reference a spectrum library from the mzTab rather than trying to bolt it on with CSV within TSV, but I can see potential use cases for the latter.

**Comment by edeutsch** [comment]
Also, note that while masses and intensities can be comma separated, the interpretations as currently specified can have commas in them to permit more than one possible interpretation per peak. Therefore in mzTab, it would probably need to be semi-colon separated or similar.
We have several topics here all intermingled.

**Comment by ypriverol** [comment]
> Also, note that while masses and intensities can be comma separated, the interpretations as currently specified can have commas in them to permit more than one possible interpretation per peak. Therefore in mzTab, it would probably need to be semi-colon separated or similar.
> We have several topics here all intermingled.

I think I will go for the reference to the file. At the moment to an MSP and when our speclib is ready to the speclib file format.
