### ISSUE TITLE
New extension for the file format

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzSpecLib#5]
As we discuss today (PSI2018 Meeting). One of the starting points would be to change the extension of the format as proposed. I recommend starting adding possible name he and people can vote on the comment using +1 or the icon for voting. 

Please whatever proposal you made, check first this site that the file extension does not exists https://fileinfo.com/extension/msp

**Comment by ypriverol** [comment]
If we follow the same path of previous approaches formats we can use the extension: **mzl** 

I have chack and the extension do not exists.

**Comment by ypriverol** [comment]
Ping @sneumann @jshofstahl @henryhlam

**Comment by jshofstahl** [comment]
The slif (spectral library import format) that I suggested, also doesn't exists.  The mzl I would assume equates to "mass spec library"

**Comment by ypriverol** [comment]
Thanks @jshofstahl we have then two proposals: 

mzl : mass spectral library 
slif: spectral library import format

**Comment by sneumann** [comment]
I don't care too much about the extension naming, I like both.

**Comment by schymane** [comment]
mzl could get potentially confusing with mzML, mzXML etc ... but I prefer it to a slif which sounds strange. Why just an import format? what about slf (I am likely missing a lot of background...)?

**Comment by rsalek** [comment]
if had to vote, I would vote .mzl than .slif (my auto correction keeps changing it into slim!)

**Comment by edeutsch** [comment]
what about .mzLib? hmm, but it looks like there's already a software library called mzLib
or how about .slib? doesn't seem to have any conflicts
or .mzslib? nothing prior there
or .mzlf? no priors there

**Comment by ypriverol** [comment]
mzl : mass spectra library
slif  : spectral library import format 
slib : spectral library
mzslib : mass spectral library
mzlf: mass spectral library format

**Comment by jgriss** [comment]
+1 for mzlf

I'd stick with the "mz" to highlight it's a mass spec based format. Also, it's in-line with all the other PSI formats.

**Comment by rsalek** [comment]
+1 mzl

**Comment by ypriverol** [comment]
@mwang87 can you provide your feedback here.

**Comment by schymane** [comment]
I agree with Ming, mzl is good but I agree with the previous comment that it's not obvious it's a library, mzlb is actually quite ok ...




On Sun, Apr 22, 2018 at 9:22 AM +0200, "Ming Wang" <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 for mzl, though I would lean toward Henry's suggestion of mzlb a bit more.

**Comment by ypriverol** [comment]
ok: mzlb look now like a good option. Please give a +1 here if you agree with it.

**Comment by RalfG** [comment]
During the 2020 Spring Meeting and following calls, the name mzSpecLib with extension `.mzlb` (in analogy to mzIdentML/`.mzid`) was chosen. This also matches the previous consensus on the `.mzlb` file extension.
