### ISSUE TITLE
MSP Spectral Libraries To Convert

### ISSUE THREAD

**Issue by mobiusklein** [HUPO-PSI/mzSpecLib#50]
# setup tool:
EDIT: PR merged, safe to use master
```bash
git clone https://github.com/HUPO-PSI/mzSpecLib.git
pip install ./mzSpecLib/implementations/python/
```
# conversion tool:
```bash
mzspeclib convert -f text $MSP $MZLB.TXT
```
# spectral libraries
- [ ] https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:human_skin_hair
- [ ] https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:human_hcd_tmt
- [ ] https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:phoshopept_labelfree_20190214
- [ ] https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:kustersynselected20170530

**Comment by mobiusklein** [comment]
Issues encountered on https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:clib:humanhcditraqphosphoselected20141126 which involved differences in how iTRAQ ions are annotated.
```
110.0717	10894	"a5-iTRAQ^3/8.2ppm"
114.1108	55509.4	"iTRAQ114/0.9ppm"
```

**Comment by mobiusklein** [comment]
Noticed https://github.com/HUPO-PSI/mzSpecLib/blob/master/legacy-formats/msp-files/nist-bsa_consensus.msp in the repository and tried to convert it, only to discover it's got a totally different way of annotating peaks. I tied the MSP regex in knots to make it work, but cannot find an MSP file on NIST's website that resembles this file. Does anyone know its source?

**Comment by polyvidian** [comment]
I dug around and found this:

https://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:bsa_it

I'll have to ask around the group to ascertain its provenance though.

**Comment by mobiusklein** [comment]
@hechth volunteered?

**Comment by hechth** [comment]
@mobiusklein yeah I will check this out over the next week and try to run some of the conversions

**Comment by hechth** [comment]
@mobiusklein I'm trying to run the conversions and I'm getting the following error:

```ModuleNotFoundError: No module named 'mzlib.index'```

Maybe some problem with the import paths? I followed the procedure described above, but I am running it on Windows - if that is not supported I can also try it on linux.

**Comment by mobiusklein** [comment]
Found the issue, the `setup.py` wasn't using `setuptools.find_pacakges` to recursively expand submodules. Please try again with the updated branch.

**Comment by hechth** [comment]
So I actually ran conversion of those libraries and also the proteomics ones listed above. I attached the converted outputs and error messages - I didn't inspect it yet in more detail.
[coversion_results_and_bug_reports.zip](https://github.com/HUPO-PSI/mzSpecLib/files/10246657/coversion_results_and_bug_reports.zip)

**Comment by mobiusklein** [comment]
@hechth Thank you for uploading those libraries and trying to convert them. You were right, they are _totally_ different from what I've been testing with. I've updated the branch to make the MSP parser compatible with them, to a point.

A few things noted:
1. We have a CV term for InCHIKey (MS:1002894), the checksum of a canonical InCHI encoded molecule, but not a term for the InCHI encoding itself. This affected the MoNA dataset.
2. Some of the MSPs have multiple redundant attributes like `MW`, `exact mass`, and `total exact mass`. I mapped all of these to `MS:1000224|molecular mass`, though I recognize that they might have distinct semantics for the intended consumer of the MSP (also the MoNA dataset). I deduplicate them and the `MS:1000866|molecular formula` attribute where possible hashing the attribute value and the group ID, favoring the longest, most precise representation first.
3. Some Comment lines were key-value pairs, others were just prose and there was no way to tell the difference reliably. I considered counting how many entries were key-value and how many were not but decided to hold off on trying to guess for now. The MSDIAL library had this problem.
4. When there were peak annotations, they were also prose, not a compact notation which necessitated making the annotation-and-aggregation collection more complicated. This was the test_gcms_metabolomics library.
5. Sometimes there were multiple peaks on a line delimited by a `;` without any annotations. This also required "unrolling" peak lines in a loop. SAMPLE_SPECTRUM_METABOLOMICS_NIST_EXPORT was the only example of that I saw.

The extreme issues were fixed on the branch and it can parse and convert those libraries, but many of the attributes don't map to a CV term yet.

[mzSpecLibTestData_JK.zip](https://github.com/HUPO-PSI/mzSpecLib/files/10297128/mzSpecLibTestData_JK.zip)

I will repeat the peptide library tests to make sure that they are still working.

**Comment by hechth** [comment]
@mobiusklein that's great - yeah the peak annotations aren't standardized for small molecules (or at least I am not aware of any standard) which makes it complicated to parse them.

**Comment by meowcat** [comment]
Hi,
Have you tried to parse the MassBank msp (we have them in NIST and RIKEN MSP "flavors")?
https://github.com/MassBank/MassBank-data/releases/tag/2022.12

At some point the question would be if it is feasible to parse MassBank format directly (with efforts from your and/or our side), but this would be a first try.

**Comment by mobiusklein** [comment]
I wasn't aware those were available. I can already see I'll need to make a few of the attribute handlers for MSP more robust to handle certain things to make them work.

**Comment by edeutsch** [comment]
This is implemented in https://github.com/HUPO-PSI/mzSpecLib/blob/master/implementations/python/bench/nist_msp_ftp_test.py
closing.
