### ISSUE TITLE
Implementation detail: What does finding `library spectrum index` mean for the a library reader?

### ISSUE THREAD

**Issue by mobiusklein** [HUPO-PSI/mzSpecLib#69]
We have three explicit unique identifiers for a `library spectrum`: `key`, `name`, and `index`. 
- The `key` is supposed to be a stable numeric identifier, akin to a "primary key" in a database, where the cardinality of the key is historical rather than positional. In theory, should you re-order a library, the `key` doesn't change.
- The `name` is a theoretically human readable name that describes the spectrum chosen by its creator, which means that it is essentially free text when not stipulated by the source format (e.g. MSP). It should be unique too, leaving it up to the creator to figure out how to make it clear to a human.
- The `index` is supposed to be an externally "unstable" identifier for a spectrum within the library, specifying an ordinal number starting from 0. As read, should you re-order a library, the `index` _does_ change.

When reading a library, the parser "knows" how many spectra preceded the spectrum it is currently parsing, and so it can automatically "fill in" the `index` attribute and the authors of a library needn't include it. However, we have explicitly written that it may be included in the output:
> Optionally, a library spectrum index (MS:1003062) MAY be included to refer to the ordered position of the spectrum within the library, starting with 0 for the first spectrum. A library spectrum may have its index changed as the library evolves, and therefore SHOULD only be used internally by the library management software (e.g. for random access retrieval). To refer to a library spectrum unambiguously from outside (e.g. using a Universal Spectrum Identifier), the library spectrum key MUST be used. 

Should that mean that if a parser reads an `index` attribute, it's obligated to store it and round-trip it, while also generating its own internal `index` separately? This is undefined behavior, according to one reading of the spec. Another more restrained reading might suggest that the value `index` refers to is never actually taken from the source file verbatim but inferred, and so any read value should be ignored because it constitutes information external to the layout of the library itself.

```obo
[Term]
id: MS:1003062
name: library spectrum index
def: "Integer index value that indicates the spectrum's ordered position within a spectral library. By custom, index counters should begin with 0." [PSI:PI]
is_a: MS:1003234 ! library spectrum attribute
relationship: has_value_type xsd:integer ! The allowed value-type for this CV term
```
Suppose we parse this:
```xml
<Spectrum=3>
MS:1003062|library spectrum index=0
...
<Spectrum=1>
MS:1003062|library spectrum index=1
...
<Spectrum=4>
MS:1003062|library spectrum index=1000
```
The first two entries' `index` attributes match their true coordinates in the sequence of library spectra, but the third spectrum's `index` is totally different (2 vs. 1000). What should the parser do? I'd argue that it is context-dependent.

If I were writing a spectrum viewing application, I'd theoretically include the `index` in the text rendering of the spectrum so that the user knows where in the file an entry is. If I then parsed that text back into the program, I'd probably want to respect that value because I wouldn't know if I were just passing that object around to just be shown elsewhere (e.g. sent to a web app to be rendered again, or passed around via federated PROXI requests) where that index information is just as salient as if it were presented locally. I'd treat that index value as something to display, but it'd be ignored for the purposes of _actually_ looking that single spectrum up again.

However, were I writing a library manipulation tool that's not so interactive, I'd probably say "any buffer of one or more spectra constitutes a single library" and want that library to be internally consistent and ignore the input `index` value. After all, if the user wants to split a library transform parts differently, and re-merge them, they'll just get re-indexed anyway. Especially if the user merges two separate libraries, not slices of the same library.

Can we say explicitly which reading is more accurate, or that both usages are acceptable and it is up to the implementer to choose which way to go?

**Comment by edeutsch** [comment]
I don't think I understand exactly what the two options here are. Can you state them a bit more clearly?

I am thinking: if software tool X is not sure that it generated a particular index value itself (i.e. it came from somewhere else or there is doubt), then software tool X is not under any obligation to preserve that index value, and may freely replace the value with whatever value it thinks is appropriate for its library management needs.

**Comment by hechth** [comment]
Is there any clear benefit in reading user defined indices over just discarding them / overwriting it with a 0-n index? We do assume that the `key` is user defined, right?

**Comment by edeutsch** [comment]
This is described on page 16 of the current spec, so this is fine. closing.
